### ISSUE TITLE
pt_pred != tf_pred

### ISSUE THREAD

**Issue by splinter21** [w-hc/torch_audioset#1]
tf.__version__ : 2.0 (gpu)
torch.__version__: 1.2.0

python setup.py install

convert_yamnet.py: sys.path.append(path_yamnet)
python convert_yamnet.py

(5, 521)
(5, 521)
'''
    print(pt_pred.mean(), pt_pred.std())
    print(tf_pred.mean(), tf_pred.std())
'''
-42.964317 20.943628
0.007766822 0.08558724
'''
assert np.allclose(pt_pred, tf_pred, atol=1e-6)
'''
Traceback (most recent call last):
  File "convert_yamnet.py", line 159, in <module>
    main()
  File "convert_yamnet.py", line 153, in main
    assert np.allclose(pt_pred, tf_pred, atol=1e-6)
AssertionError

**Comment by w-hc** [comment]
I will investigate this problem later. But for now you can use the converted weights I provided in the release. It works pretty well.

**Comment by splinter21** [comment]
> I will investigate this problem later. But for now you can use the converted weights I provided in the release. It works pretty well.

Thanks! I will have a try.

**Comment by Honghe** [comment]
@splinter21 How do you address this problem?

**Comment by w-hc** [comment]
with @Honghe 's help the issue should be resolved for the latest version.
